apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      name: hello-go
      labels:
        app: hello-go
    spec:
      containers:
        - image: gcr.io/tk-dev-micro/hello-go-bintang
          name: hello-go-server
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
