apiVersion: v1
kind: Service
metadata:
  name: hello-go
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: hello-go