name: Deploy to GKE


on: [push]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dev-hello-go-test
  GKE_ZONE: asia-southeast1-a
  DEPLOYMENT_NAME: gke-deployment

jobs:
  # setup-build-publish-deploy:
  #   name: Setup, Build, Publish, and Deploy
  #   runs-on: ubuntu-latest
  #   # environment: production
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
  #       with:
  #         service_account_key: ${{ secrets.GKE_SA_KEY }}
  #         project_id: ${{ secrets.GKE_PROJECT }}

  #     - run: |-
  #         gcloud --quiet auth configure-docker

  #     - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
  #       with:
  #         cluster_name: ${{ env.GKE_CLUSTER }}
  #         location: ${{ env.GKE_ZONE }}
  #         credentials: ${{ secrets.GKE_SA_KEY }}

  #     - run: |-
  #         kubectl

  ruin:
    name: ruinin njay
    runs-on: ubuntu-latest

    steps:
      - run: |-
          kubectl
